services:
  thb:
    image: thb-image:latest
    container_name: thb
    restart: always
    network_mode: host
    working_dir: /app
    env_file: .env
    volumes:
      - ./thb.jar:/app/app.jar:ro
      - ./data:/app
    entrypoint: ["java", "-jar", "/app/app.jar"]
